### ISSUE TITLE
telethon.errors.rpcerrorlist.FloodWaitError

### ISSUE THREAD

**Issue by smartmanru** [SlavikMIPT/opentfd#3]
`Traceback (most recent call last):
  File "opentfd.py", line 27, in <module>

  File "site-packages/telethon/client/auth.py", line 110, in start
  File "asyncio/base_events.py", line 468, in run_until_complete
  File "site-packages/telethon/client/auth.py", line 134, in _start
  File "site-packages/telethon/client/auth.py", line 350, in send_code_request
  File "site-packages/telethon/client/users.py", line 33, in __call__
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 73409 seconds is required
[2024] Failed to execute script opentfd`

**Comment by SlavikMIPT** [comment]
слишком много попыток авторизации
