### ISSUE TITLE
Ubuntu ssl error 

### ISSUE THREAD

**Issue by smartmanru** [SlavikMIPT/opentfd#4]
Авторизация прошла успешно, но после нее такая ошибка
 root@ubuntu-s-1vcpu-1gb-fra1-01  ~/opentfd  ./opentfd-linux-noproxy
Traceback (most recent call last):
  File "urllib/request.py", line 1318, in do_open
  File "http/client.py", line 1239, in request
  File "http/client.py", line 1285, in _send_request
  File "http/client.py", line 1234, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 964, in send
  File "http/client.py", line 1400, in connect
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 814, in __init__
  File "ssl.py", line 1068, in do_handshake
  File "ssl.py", line 689, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opentfd.py", line 30, in <module>
    async def typing_handler(event):
  File "mtranslate/core.py", line 80, in translate
  File "urllib/request.py", line 223, in urlopen
  File "urllib/request.py", line 532, in open
  File "urllib/request.py", line 642, in http_response
  File "urllib/request.py", line 564, in error
  File "urllib/request.py", line 504, in _call_chain
  File "urllib/request.py", line 756, in http_error_302
  File "urllib/request.py", line 526, in open
  File "urllib/request.py", line 544, in _open
  File "urllib/request.py", line 504, in _call_chain
  File "urllib/request.py", line 1361, in https_open
  File "urllib/request.py", line 1320, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
[16529] Failed to execute script opentfd
 root@ubuntu-s-1vcpu-1gb-fra1-01  ~/opentfd         ✘   master ● ?  03:16:12

**Comment by SlavikMIPT** [comment]
443 порт открыт?
